### ISSUE TITLE
Week number.

### ISSUE THREAD

**Issue by patwcollins** [R-CoderDotCom/calendR#1]
Would it be possible to be make it possible to add a week number of the year for each week?

**Comment by R-CoderDotCom** [comment]
@patwcollins Thaks for the suggestion. The package has been updated. Now you can set `week.number = TRUE` to add the week numbers to all types of calendars. You can also customize its color and the font size of the numbers with the `week.number.col` and `week.number.size` arguments, respectively. The functionality will bea available on CRAN on the next release
