### ISSUE TITLE
Specify number of columns for calendar

### ISSUE THREAD

**Issue by Nova-Scotia** [R-CoderDotCom/calendR#10]
Hi there, loving the simplicity of this package. Thank you :). I'd like to create calendars that are stacked in a single column - for example, four months vertically on top of each other. I know that I could do this using `cowplot` or `patchwork`, but it seems like it might be a simple tweak to allow a user to specify a `ncol` argument within the function to use within `facet_wrap` instead of using `orientation`, which forces users to accept `ncol` = 3 or 4. You might even use `case_when` so that if users specify `portrait` or `landscape` the function chooses the appropriate `ncol`, but if they specify `ncol` that number is preferentially chosen.

**Comment by R-CoderDotCom** [comment]
Hi! Sorry for the late response. I forgot solving this issue, sorry :(

Someone asked me the same today and I updated the code. Now it is possible to specify the number of columns with `ncol`. This argument will override the `orientation` argument. :)

```r
calendR(ncol = 2)
```

![imagen](https://user-images.githubusercontent.com/67192157/130368869-db75fd79-734a-441c-b62b-7ed866456c71.png)
