### ISSUE TITLE
shiny app with calendR

### ISSUE THREAD

**Issue by rjnkapoor** [R-CoderDotCom/calendR#11]
Hi I am trying to make a shiny app and use calendR with text (user selected input). I am getting stuck at what to put in ui and server

**Comment by R-CoderDotCom** [comment]
I haven't tried using calendR inside a Shiny app, but there are some examples around. Take a look to https://github.com/liangliangzhuang/shiny_calendar or https://github.com/jrozra200/strava_dashboard

**Comment by rjnkapoor** [comment]
Thanks a million, for prompt response and help.
