### ISSUE TITLE
Calendar frame is lost when using ggplotly()

### ISSUE THREAD

**Issue by YonghuiDong** [R-CoderDotCom/calendR#12]
Thanks for the nice package. 

I want to combine the calendar object with `ggplotly` to make it interactive, however I found the frame is missing.

Below is my example code:

```
library(calendR)
library(plotly)
data <- runif(31)
p <- calendR(year = 2021,
             month = 10,
             special.days = data,
             gradient = TRUE,
             low.col = "white",
             special.col = "#FF4600")

ggplotly(p)
```
<img width="900" alt="Screen Shot 2021-09-18 at 16 50 09" src="https://user-images.githubusercontent.com/22663189/133891120-480aa597-cc69-47bc-bfbe-267aff0bc772.png">

Could you please help fix this issue?

Thanks a lot.

Dong

**Comment by R-CoderDotCom** [comment]
Hi Dong, thank you for reporting this.

Unfortunately, fixing this doesn't depend on me. This is a known plotly issue. See https://github.com/plotly/plotly.js/issues/898 or https://stackoverflow.com/questions/56549728/using-the-color-aesthetic-with-geom-tile-in-ggplotly

**Comment by YonghuiDong** [comment]
I understand the problem now. Thanks a lot.

Dong
