### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by mschilli87** [R-CoderDotCom/calendR#15]
As discussed in #14, I am in the process of forking this repository. If I take over (some) maintenance burden and invest more time in a project than a quick patch, I prefer using strong FOSS licenses. [According to the `DESCRIPTION` file, calendR is released under the terms of the GPL-2](https://github.com/R-CoderDotCom/calendR/blob/master/DESCRIPTION#L10). This is also what users will find in ` packageDescription("calendR")` after installing `calendR` from CRAN.
However, the  source files themselves don't contain any copyright and licensing statements (as required by the GPL) and [the `LICENSE` file contains the MIT license](https://github.com/R-CoderDotCom/calendR/blob/master/LICENSE) instead. So should I consider `calendR` dual-licensed under the MIT and GPL-2 license? Is this GPL version 2 only or GPL version 2 or any later version? IANAL but AFAIK the MIT license allows sub-licensing so I could release my fork under GPL version 3 anyways but I want to make sure I understand the intentions of the copyright holders before publishing any of my changes. I just want to cover my bases here and try not to step on anyone's toes. So any clarification would be highly appreciated.
Just to clarify, my preferred license for my fork would be AGPL3+ but I would be willing to license any commit you want to cherry-pick for upstream inclusion under the GLP2-only and/or MIT license(s) because I am thankful for the work done on `calendR`, want to keep supporting this project and believe in collaboration in FOSS.

Thanks in advance for your feedback and merry Christmas,
Marcel

**Comment by R-CoderDotCom** [comment]
Hi!

You are right, so feel free to fork the repository and make any changes as long as you refer to the original authors somewhere.

Best regards

**Comment by mschilli87** [comment]
Thank you for getting back. I'll definitely make sure to give you full credit. After all I only fork to get my rejected feature in. I will go with MIT then for your code as per the LICENSE file and release my changes under AGPL3+ on top of it. If you end up-cherry picking some of my code, rest asured I'll re-license the changes for you as long as it remains FOSS. Since my vacation are over now, it might take a while until you see any activity on my fork though. :wink:
