### ISSUE TITLE
More than 12 months?

### ISSUE THREAD

**Issue by patwcollins** [R-CoderDotCom/calendR#2]
Thanks for the week numbers! This package is great. I wonder is it possible to make it capable of creating a calendar of more than 12 months? I tried setting the start_date and end_date 14 months apart but the months over-paint each other.

**Comment by R-CoderDotCom** [comment]
For that purpose you will need to use the package `cowplot` or `patchwork`. Here is an example using the second:

```
library(patchwork)

p1 <- calendR::calendR(2020)
p2 <- calendR::calendR(2021)

p1 + p2
```

![imagen](https://user-images.githubusercontent.com/67192157/95024538-e8bb3f00-0683-11eb-8e54-f5c4592cf82f.png)

Maybe we need to add a warning message if someone tries to plot more than 12 months that way, or implement the feature with the `patchwork` package. We will think about it.

**Comment by R-CoderDotCom** [comment]
I'm going to close this issue. Feel free to reopen it if you think my previous comment doesn't solve your issue.
