### ISSUE TITLE
Error "the condition has length > 1" when using example "Add Several Events"

### ISSUE THREAD

**Issue by drcanak** [R-CoderDotCom/calendR#24]
The "Add Several Events" example

https://github.com/R-CoderDotCom/calendR#add-several-events

no longer works. It throws the error:

"Error in if (special.days != "weekend") { : the condition has length > 1"

R version 4.2.3.

**Comment by R-CoderDotCom** [comment]
Hi! You are right. That happens because, by default, `calendR` uses the current year to create the calendar. That example was created in 2020 (a leap year), so for other years you just need to replace:

`myfills <- rep(NA, 366)`

with

`myfills <- rep(NA, 365)`
