### ISSUE TITLE
Weekends

### ISSUE THREAD

**Issue by msgoussi** [R-CoderDotCom/calendR#25]
I work in Saudi Arabia, and most of the Arab world their weekend are Friday and Saturday.
So I am wondering if there is a way to get a Calendar where Friday and Saturday is highlighted as the weekends.

**Comment by R-CoderDotCom** [comment]
Hi! 

It is hard to customize the funcion to achieve all the different possibilities, but the package is flexible itself to achieve what you need with only a few lines of code.

First you can get all the Fridays and Saturdays of a year with the `getDays` function and then input the result to `special.days`.

```
# year: year of the calendar
# day: 0–6 day OR days of the week, starting on Sunday.
getDays<- function(year, day) {
  start <- as.Date(paste0(year,"-01-01"))
  end <- as.Date(paste0(year,"-12-31"))
  ndays <- length(seq(start, end, by="1 day"))
  days <- as.POSIXlt(paste(year, 1:ndays, sep="-"), format="%Y-%j")
  days_position <- which(seq(start, end, by="1 day") %in% days[days$wday %in% day])
  days_position  <- days_position [!is.na(days_position)]

  return(days_position )
}

# Get the weekeneds of 2023
arab_weekends <- getDays(2023, day = c(5, 6))

# Plot the calendar
calendR(year = 2023, special.days = arab_weekends)
```


Output:

![image](https://github.com/R-CoderDotCom/calendR/assets/67192157/eb811bc1-8ca9-40c6-9e93-2e6fa71d14dc)



Hope this helps!
