### ISSUE TITLE
Individual month names

### ISSUE THREAD

**Issue by bollstef** [R-CoderDotCom/calendR#3]
Hello! First off all, this is a great package. Thanks for your work!

I really would like a way to configure an individual name for each month  - similar to the "weeknames" option. Would this be possible?

(I work with the heatmap and would be able to add an additional information into the name, for example "January (mean =8.88)"

**Comment by R-CoderDotCom** [comment]
Hey there! Thanks for the suggestion. I've added a new argument named `monthnames` to customize the name of the months. If nothing is specified, the function will work as always. Here is an example: 

`calendR(2021, monthnames = sapply(1:12, function(i) paste0(month.abb[i], " (mean = ", i, ")")))`

![imagen](https://user-images.githubusercontent.com/67192157/95106401-c1727980-0738-11eb-9908-b7eaf77ea467.png)
