### ISSUE TITLE
Is start_date not an argument anymore?

### ISSUE THREAD

**Issue by mchiapello** [R-CoderDotCom/calendR#33]
What am I doing wrong?

```
> calendR(
+     start_date = "2024-09-01",
+     end_date = "2025-05-31")
```
**Error in calendR(start_date = "2024-09-01", end_date = "2025-05-31") : 
  unused arguments (start_date = "2024-09-01", end_date = "2025-05-31")**

I saw start_date argument in previous issues.

**Comment by mschilli87** [comment]
Try `from` and `to`.
