### ISSUE TITLE
2018 starts at week 2

### ISSUE THREAD

**Issue by patwcollins** [R-CoderDotCom/calendR#4]
I ran the following code and it starts 2018 at week 2 and runs to week 54.
```
calendR(
  start_date = "2018-01-01",
  end_date = "2018-12-31",
  lty = 0,
  title = "2018",
  start = "M",
  weeknames = c("M", "T",  # Week names
                "W", "T",
                "F", "S", "S"),
  week.number = TRUE,
  week.number.col = "red")
```

**Comment by R-CoderDotCom** [comment]
Hey there, you are right. Thanks for reporting this! There are lots of combinations of arguments and it is difficult to check all of them, This issue seemed to happen when the year starts on Monday. It should be fixed now. I've tried with several combinations of years and everything seems to work. This is the output with your code:

![imagen](https://user-images.githubusercontent.com/67192157/95187261-3f7f6080-07cb-11eb-999e-07992f528b27.png)


I'm going to close this issue but feel free to reopen it if something does not work as expected.

**Comment by R-CoderDotCom** [comment]
Sorry, it is not fixed yet. Now there is an issue in 2012 when week starts on Monday because there are 54 weeks. I will try to fix it.

**Comment by R-CoderDotCom** [comment]
Code updated again. Please verify if the `week.number` argument works as expected.

**Comment by R-CoderDotCom** [comment]
I'm going to close this issue. Feel free to reopen it if the problem persists.
