### ISSUE TITLE
change legend size

### ISSUE THREAD

**Issue by ShinyFabio** [R-CoderDotCom/calendR#8]
Hello, I'm developing a shiny app and I added your calendar. I use the year view and I added "special days" with a vector. My only problem is that the text of the legend is too small and I want to increase it but I didn't find any option for the legend size.

**Comment by R-CoderDotCom** [comment]
Hi @ShinyFabio, thanks for ussing the calendR package on your Shinny app.

As the package was build with ggplot2 it is possible to change the size of the elements of the legend making use of the components of the `theme` function as follows:
```

library(ggplot2)
library(calendR)

myfills <- rep(NA, 366)

myfills[c(1:4, 50, 300:315)] <- "Holidays"
myfills[16] <- "Birthday"

calendR(year = 2020,
        special.days = myfills,
        special.col = 2:3,     
        legend.pos = "right") +
  theme(legend.key.size = unit(1, units = "cm"), # Keys size
        legend.text = element_text(size = 30))       # Text size
```

![imagen](https://user-images.githubusercontent.com/67192157/114162180-25187200-9929-11eb-9eb6-2dcae31291a6.png)


You could also change the height and the width of the legend keys independently with `legend.key.height` and `legend.key.width`.

**Comment by ShinyFabio** [comment]
Thanks! Now it's perfect.
Since the package uses ggplot2, I tried to use `ggplotly()` from plotly package, but doesn't work very well. I don't know if you have planned to integrate plotly in your package. I think will be the best calendar in R!

And I have a last question. I need also a month view adding text to some special days. I tried with `text ` option, but my problem is that I can use only a short text otherwise it will be printed in the nearby days (since text is printed on only one line). I think the only solution is to add the possibility to write text on more lines, but I don't know if it's feasible. If `ggplotly()` worked I could use a variable for the color days (like your Birthday and Holidays) and maybe uses a description variable for the tooltip (so when a cursor is positioned over the day, the description appears).

**Comment by R-CoderDotCom** [comment]
I haven't tested using `ggplotly` and I'm not sure if it can be compatible with this package. I don't know if I have to set  something special to make it work or how to make it compatible. I've thought about creating a dynamic calendar but I don't have the enough time to try it at this moment.

If you want to fit the text try using `\n` manually to break the lines or try to modify the source code substituting `geom_text` with  `geom_fit_text` (https://wilkox.org/ggfittext/). I wanted to implement this by myself but I've been working on other projects.

**Comment by R-CoderDotCom** [comment]
Going to close this issue. If you have any other suggestion reopen or open a new one.
