### ISSUE TITLE
Wrap Text

### ISSUE THREAD

**Issue by ApexHeel** [R-CoderDotCom/calendR#9]
Is it possible to specify an option to wrap the text for special days in monthly view (i.e., go to a new line)?

**Comment by R-CoderDotCom** [comment]
Hi @ApexHeel,

at this moment it is possible to add text with several lines with `\n`, as shown in the following example:

```r
calendR(month = 7, year = 2022, 
        special.days = c(1, 5, 12, 28), 
        text = "Line 1\nLine 2\nLine 3", 
        text.pos = c(1, 5, 12, 28)) 
```
Resulting into:
![imagen](https://user-images.githubusercontent.com/67192157/120533645-3e95e180-c3e1-11eb-94bb-a8ee86f0f288.png)


However, it the text is too big it might overflow. In that scenario, you should increase the size of the calendar or make the font smaller.

**Comment by ApexHeel** [comment]
That's perfect for my needs. Thank you!
